name: Verify requirements.txt exists

on:
  push:
    branches:
      - main

jobs:
  check-requirements:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: List files in main-site/api
      run: ls -la main-site/api/
