name: Rebuild and deploy comments microservice

on:
  push:
    branches:
      - main
    paths:
      - 'comments/**'
  workflow_dispatch:

jobs:
  
  # Rebuild container image and push to acr
  build-image-and-push-to-acr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: SSERecipeContainers.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build ./comments -t SSERecipeContainers.azurecr.io/sse-comments-container:latest
          docker push SSERecipeContainers.azurecr.io/sse-comments-container:latest
  
  # Delete old contain instance and redeploy
  deploy-image-as-aci:
    runs-on: ubuntu-latest
    needs: build-image-and-push-to-acr
    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Delete existing Azure Container Instance
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az container delete --name sse-comments-container --resource-group SSE-recipe --yes || true

      - name: Deploy new Azure Container Instance
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az container create \
              --resource-group SSE-recipe \
              --name sse-comments-container \
              --image SSERecipeContainers.azurecr.io/sse-comments-container:latest \
              --dns-name-label sse-comments \
              --ports 5000 5001 1433 \
              --registry-login-server SSERecipeContainers.azurecr.io \
              --registry-username ${{ secrets.ACR_USERNAME }} \
              --registry-password ${{ secrets.ACR_PASSWORD }} \
              --environment-variables FLASK_ENV="production" COMMENTS_DRIVER="${{ secrets.COMMENTS_DRIVER }}" COMMENTS_SERVER="${{ secrets.COMMENTS_SERVER }}" COMMENTS_DATABASE="${{ secrets.COMMENTS_DATABASE }}" COMMENTS_USERNAME="${{ secrets.COMMENTS_USERNAME }}" COMMENTS_PASSWORD="${{ secrets.COMMENTS_PASSWORD }}"
