name: Rebuild and deploy main-site web app


on:
  push:
    branches:
      - main
    paths:
      - 'main-site/**'
  workflow_dispatch:

jobs:
  # Build the server for the main site and upload as an artifact to pull in the deploy job
  build-main-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'

      - name: Install dependencies and list packages
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r main-site/api/requirementscopy.txt
          pip list

      - name: Install dependencies
        run: pip install -r main-site/requirements.txt

      # - name: Run pytest
      #   run: |
      #     source venv/bin/activate
      #     PYTHONPATH=./main-site pytest main-site/tests

      - name: Zip artifact for deployment
        run: zip -r release.zip ./*
        working-directory: main-site/api

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: main-site/api/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build-main-site
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'YourRecipeWorld'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_432E0FF062964311A6EB42BBF78A9DE7 }}
