name: Rebuild and deploy main-site web app


on:
  push:
    branches:
      - main
    paths:
      - 'main-site/**'
  workflow_dispatch:

jobs:
  # Build the server for the main site and upload as an artifact to pull in the deploy job
  build-main-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'

      - name: Install dependencies and list packages
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r main-site/requirements.txt
          pip list

      - name: Run pytest
        run: |
          source venv/bin/activate
          PYTHONPATH=./main-site pytest main-site/tests
        continue-on-error: true

      - name: Zip artifact for deployment
        run: zip -r release.zip ./*
        working-directory: main-site/api

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: main-site/api/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build-main-site
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'YourRecipeWorld'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_432E0FF062964311A6EB42BBF78A9DE7 }}
          
      - name: Set environment variables in Azure Web App
        run: |
          az webapp config appsettings set --name YourRecipeWorld --resource-group SSE-recipe --settings "FLASK_KEY=${{ secrets.FLASK_KEY }}" "AUTHENTICATION_DRIVER=${{ secrets.AUTHENTICATION_DRIVER }}" "AUTHENTICATION_SERVER=${{ secrets.AUTHENTICATION_SERVER }}" "AUTHENTICATION_DATABASE=${{ secrets.AUTHENTICATION_DATABASE }}" "AUTHENTICATION_USERNAME=${{ secrets.AUTHENTICATION_USERNAME }}" "AUTHENTICATION_PASSWORD=${{ secrets.AUTHENTICATION_PASSWORD }}"
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
