name: Rebuild and deploy user-details microservice

on:
  push:
    branches:
      - main
    paths:
      - 'user-details/**'
  workflow_dispatch:

jobs:
 
  test-user-details:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest 
          pip install -r user-details/requirements.txt # Assuming you have a requirements file

      - name: Run pytest
        run: |
          PYTHONPATH=./user-details pytest user-details/tests
  
  # Rebuild container image and push to acr
  build-image-and-push-to-acr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: SSERecipeContainers.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build ./user-details -t SSERecipeContainers.azurecr.io/sse-user-details-container:latest
          docker push SSERecipeContainers.azurecr.io/sse-user-details-container:latest
  
  # Delete old contain instance and redeploy
  deploy-image-as-aci:
    runs-on: ubuntu-latest
    needs: build-image-and-push-to-acr
    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Delete existing Azure Container Instance
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az container delete --name sse-user-details-container --resource-group SSE-recipe --yes || true

      - name: Deploy new Azure Container Instance
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az container create \
              --resource-group SSE-recipe \
              --name sse-user-details-container \
              --image SSERecipeContainers.azurecr.io/sse-user-details-container:latest \
              --dns-name-label sse-user-details \
              --ports 5000 5001 1433 \
              --registry-login-server SSERecipeContainers.azurecr.io \
              --registry-username ${{ secrets.ACR_USERNAME }} \
              --registry-password ${{ secrets.ACR_PASSWORD }} \
              --environment-variables FLASK_ENV="production" USER_DETAILS_DRIVER="${{ secrets.USER_DETAILS_DRIVER }}" USER_DETAILS_SERVER="${{ secrets.USER_DETAILS_SERVER }}" USER_DETAILS_DATABASE="${{ secrets.USER_DETAILS_DATABASE }}" USER_DETAILS_USERNAME="${{ secrets.USER_DETAILS_USERNAME }}" USER_DETAILS_PASSWORD="${{ secrets.USER_DETAILS_PASSWORD }}"
